[workspace]
members = ["crates/seashell-core"]
exclude = ["programs/account-loader", "programs/sysvar", "programs/create-account", "programs/sysvar-ixns"]
resolver = "2"

[workspace.dependencies]
agave-feature-set = { version = "=4.3.0-alpha.3", features = ["agave-unstable-api"] }
agave-precompiles = { version = "=4.3.0-alpha.3", features = ["agave-unstable-api"] }
bincode = "^1"
ed25519-dalek = "=1.0.1"
flate2 = "^1"
indexmap = "^2"
libsecp256k1 = "^0.6"
log = "^0.4"
openssl = "^0.10"
parking_lot = "^0.12"
rand = "^0.7"
serde = "^1"
serde_json = "^1"
serde_with = { version = "^3", features = ["hex"] }
solana-account = "^4.3"
solana-bpf-loader-program = { version = "=4.3.0-alpha.3", default-features = false, features = ["agave-unstable-api"] }
solana-builtins = { version = "=4.3.0-alpha.3", features = ["agave-unstable-api"] }
solana-clock = "^3"
solana-compute-budget = { version = "=4.3.0-alpha.3", features = ["agave-unstable-api"] }
solana-ed25519-program = "^3"
solana-epoch-rewards = "^3"
solana-epoch-schedule = "^3"
solana-hash = "^4.5"
solana-instruction = "^3"
solana-instructions-sysvar = { version = "^4", features = ["dev-context-only-utils"] }
solana-logger = "^2.3"
solana-precompile-error = "^3"
solana-program-runtime = { version = "=4.3.0-alpha.3", features = ["agave-unstable-api", "dev-context-only-utils"] }
solana-pubkey = "^4.2"
solana-rent = "^4.3"
solana-rpc-client = { version = "=4.3.0-alpha.3", default-features = false }
solana-rpc-client-api = "=4.3.0-alpha.3"
solana-sdk-ids = "^3"
solana-secp256k1-program = "^3"
solana-secp256r1-program = "^3"
solana-slot-hashes = "^3"
solana-stake-interface = "^4.3"
solana-svm-callback = { version = "=4.3.0-alpha.3", features = ["agave-unstable-api"] }
solana-svm-log-collector = { version = "=4.3.0-alpha.3", features = ["agave-unstable-api"] }
solana-svm-timings = { version = "=4.3.0-alpha.3", features = ["agave-unstable-api"] }
solana-syscalls = { version = "=4.3.0-alpha.3", default-features = false, features = ["agave-unstable-api"] }
solana-sysvar = "^4.1"
solana-sysvar-id = "^3"
solana-transaction-context = { version = "=4.3.0-alpha.3", features = ["agave-unstable-api", "bincode", "dev-context-only-utils"] }
tempfile = "^3"
thiserror = "^2"
